version: '3.1'

services:
  web:
    build: .
    ports:
      - "3000:3000"
  web-client:
    build: ./frontend/
    ports:
      - "2404:2404"
    links:
      - web
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: akshit

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
